Vagrant.configure(2) do |config|
	config.vm.box = "box-cutter/ubuntu1404-desktop"
	config.vm.provider "virtualbox" do |vb|
			vb.gui = true
			vb.memory = "2048"
			vb.name="fujaba"
		end
	config.vm.provision "shell", inline: <<-SHELL
		gsettings set org.gnome.desktop.screensaver lock-enabled false
		sudo apt-get update
		
		echo "Innstalling java version 8...."
		add-apt-repository ppa:webupd8team/java
		sudo apt-get update -qq
		echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
		echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
		apt-get install --yes oracle-java8-installer
		yes "" | apt-get -f install

		sudo apt-get install unzip

# tool download section


# Obtain required Desktop files for VM
echo "Fetching eclipse files for MechatronicUML tool"

cd /home/vagrant/Desktop
sudo wget -O /home/vagrant/Desktop/eclipse.tar.gz "https://googledrive.com/host/0B8-9cnK0Fc6hRzJ4V2REc1BfZDg/eclipse.tar.gz"
tar xvzf eclipse.tar.gz
rm -f eclipse.tar.gz
# sudo chmod 777 -R /home/vagrant/Desktop/*
sudo ln -s eclipse/eclipse /usr/bin/eclipse


# Create an application launcher for Eclipse (to launch it on startup)
sudo touch /usr/share/applications/eclipse.desktop
sudo echo "[Desktop Entry]" >> /usr/share/applications/eclipse.desktop
sudo echo "Version=4.4" >> /usr/share/applications/eclipse.desktop
sudo echo "Name=Eclipse" >> /usr/share/applications/eclipse.desktop
sudo echo "Comment=Integrated Development Environment" >> /usr/share/applications/eclipse.desktop
sudo echo "Exec=/home/vagrant/Desktop/eclipse/eclipse -clean -data /home/vagrant/Desktop/workspace -vm /usr/lib/jvm/java-7-oracle/bin/java" >> /usr/share/applications/eclipse.desktop
sudo echo "Type=Application" >> /usr/share/applications/eclipse.desktop
sudo echo "Icon=/opt/eclipse/icon.xpm" >> /usr/share/applications/eclipse.desktop
sudo echo "Terminal=false" >> /usr/share/applications/eclipse.desktop
sudo echo "NoDisplay=false" >> /usr/share/applications/eclipse.desktop
sudo echo "Categories=Development;IDE" >> /usr/share/applications/eclipse.desktop
sudo chmod +x /usr/share/applications/eclipse.desktop
sudo update-desktop-database


#sudo wget -O /home/vagrant/Desktop/vm-files.tar.gz "https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-Atlas/raw/master/build-vm/vm-files.tar.gz"
#tar zxvf /home/vagrant/Desktop/vm-files.tar.gz -C /home/vagrant/Desktop/
#sudo rm /home/vagrant/Desktop/vm-files.tar.gz
#sudo chmod 775 /home/vagrant/Desktop/*
#pwd

# Start Eclipse on startup (Add Eclipse to startup)
#cd /home/vagrant/.config/
#mkdir autostart
#sudo cp /usr/share/applications/eclipse.desktop /home/vagrant/.config/autostart/



SHELL

end